2024.07.03 (수) - DAY2 데이터 활용 및 구현 2 / 이론 실습

https://www.kaggle.com/datasets/rabieelkharoua/predict-customer-purchase-behavior-dataset

In [1]:
!pip install kaggle

Requirement already satisfied: kaggle in /usr/local/lib/python3.10/dist-packages (1.6.17)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.10/dist-packages (from kaggle) (1.16.0)
Requirement already satisfied: certifi>=2023.7.22 in /usr/local/lib/python3.10/dist-packages (from kaggle) (2024.7.4)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.10/dist-packages (from kaggle) (2.8.2)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from kaggle) (2.31.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from kaggle) (4.66.4)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.10/dist-packages (from kaggle) (8.0.4)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.10/dist-packages (from kaggle) (2.0.7)
Requirement already satisfied: bleach in /usr/local/lib/python3.10/dist-packages (from kaggle) (6.1.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.10/dist-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.10/dist-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->kaggle) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->kaggle) (3.7)

In [2]:
!kaggle datasets download -d rabieelkharoua/predict-customer-purchase-behavior-dataset

Dataset URL: https://www.kaggle.com/datasets/rabieelkharoua/predict-customer-purchase-behavior-dataset
License(s): Attribution 4.0 International (CC BY 4.0)
Downloading predict-customer-purchase-behavior-dataset.zip to /content
  0% 0.00/35.1k [00:00<?, ?B/s]
100% 35.1k/35.1k [00:00<00:00, 11.8MB/s]

In [3]:
!unzip predict-customer-purchase-behavior-dataset.zip

Archive:  predict-customer-purchase-behavior-dataset.zip
  inflating: customer_purchase_data.csv

In [4]:
# pandas 라이브러리 사용
import pandas as pd

# CSV load
data = pd.read_csv('customer_purchase_data.csv')

In [5]:
# 데이터 구조 확인
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Age                 1500 non-null   int64
 1   Gender              1500 non-null   int64
 2   AnnualIncome        1500 non-null   float64
 3   NumberOfPurchases   1500 non-null   int64
 4   ProductCategory     1500 non-null   int64
 5   TimeSpentOnWebsite  1500 non-null   float64
 6   LoyaltyProgram      1500 non-null   int64
 7   DiscountsAvailed    1500 non-null   int64
 8   PurchaseStatus      1500 non-null   int64
dtypes: float64(2), int64(7)
memory usage: 105.6 KB

In [6]:
# 데이터 샘플 확인
data.head(5)

,Age,Gender,AnnualIncome,NumberOfPurchases,ProductCategory,TimeSpentOnWebsite,LoyaltyProgram,DiscountsAvailed,PurchaseStatus
0,40,1,66120.267939,8,0,30.568601,0,5,1
1,20,1,23579.773583,4,2,38.240097,0,5,0
2,27,1,127821.306432,11,2,31.633212,1,0,1
3,24,1,137798.623120,19,3,46.167059,0,4,1
4,31,1,99300.964220,19,1,19.823592,0,0,1

In [7]:
# 데이터 기초통계 확인
data.describe()

,Age,Gender,AnnualIncome,NumberOfPurchases,ProductCategory,TimeSpentOnWebsite,LoyaltyProgram,DiscountsAvailed,PurchaseStatus
count,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.00000
mean,44.298667,0.504667,84249.164338,10.420000,2.012667,30.469040,0.326667,2.555333,0.43200
std,15.537259,0.500145,37629.493078,5.887391,1.428005,16.984392,0.469151,1.705152,0.49552
min,18.000000,0.000000,20001.512518,0.000000,0.000000,1.037023,0.000000,0.000000,0.00000
25%,31.000000,0.000000,53028.979155,5.000000,1.000000,16.156700,0.000000,1.000000,0.00000
50%,45.000000,1.000000,83699.581476,11.000000,2.000000,30.939516,0.000000,3.000000,0.00000
75%,57.000000,1.000000,117167.772858,15.000000,3.000000,44.369863,1.000000,4.000000,1.00000
max,70.000000,1.000000,149785.176481,20.000000,4.000000,59.991105,1.000000,5.000000,1.00000

In [8]:
# 결측값 확인
missing_values = data.isnull().sum()
print("Missing values in each column:\n", missing_values)

Missing values in each column:
 Age                   0
Gender                0
AnnualIncome          0
NumberOfPurchases     0
ProductCategory       0
TimeSpentOnWebsite    0
LoyaltyProgram        0
DiscountsAvailed      0
PurchaseStatus        0
dtype: int64

In [9]:
import numpy as np

# 결측값 반환 함수
def add_missing_values(df, col_name, missing_frac):
    """
    특정 열에 지정된 비율의 결측값을 추가합니다.

    :param df: 데이터 프레임
    :param col_name: 결측값을 추가할 열 이름
    :param missing_frac: 결측값 비율 (0.0 ~ 1.0)
    """

    np.random.seed(42) # 재현성을 위해 랜덤 시드 설정
    n_rows = df.shape[0] # 데이터프레임의 행 수
    n_missing = int(n_rows * missing_frac) # 비율에 따라 결측값을 추가할 행의 수를 계산

    missing_indices = np.random.choice(n_rows, n_missing, replace=False) # 결측값을 추가할 행의 인덱스를 무작위로 선택
    df.loc[missing_indices, col_name] = np.nan # 선택된 인덱스의 열(col_name)에 NaN 값을 할당하여 결측값을 추가

missing_frac은 함수 add_missing_values를 호출할 때 인자로 전달됩니다. 이 인자는 결측값을 추가할 비율을 지정하며, 0.0과 1.0 사이의 값이어야 합니다. missing_frac이 0.0이면 결측값이 추가되지 않고, 1.0이면 해당 열의 모든 값이 결측값으로 설정됩니다. 사용자는 이 인자를 통해 원하는 결측값 비율을 설정할 수 있습니다.

In [10]:
# 결측값 추가
add_missing_values(data, 'Age', 0.1) # Age 열에 10% 결측값 추가
add_missing_values(data, 'Gender', 0.1) # Gender 열에 10% 결측값 추가

In [11]:
# 결측값이 잘 추가되었는지 확인
print("Data with missing values:\n", data.tail(10))

Data with missing values:
        Age  Gender   AnnualIncome  NumberOfPurchases  ProductCategory  \
1490   NaN     NaN   83126.660956                 20                3
1491   NaN     NaN   71611.955361                 20                1
1492  63.0     0.0   71874.591294                 10                2
1493  34.0     1.0   20418.374269                  9                1
1494  34.0     1.0  104649.186035                 14                1
1495  39.0     1.0   65048.141834                 13                0
1496  67.0     1.0   28775.331069                 18                2
1497  40.0     1.0   57363.247541                  7                4
1498  63.0     0.0  134021.775532                 16                2
1499  50.0     0.0   52625.665974                 13                0

      TimeSpentOnWebsite  LoyaltyProgram  DiscountsAvailed  PurchaseStatus
1490            2.280306               0                 1               0
1491           38.681686               0                 5               1
1492           43.546243               0                 1               0
1493           54.459955               0                 0               0
1494           28.998117               0                 1               0
1495           34.590743               0                 5               1
1496           17.625707               0                 1               1
1497           12.206033               0                 0               0
1498           37.311634               1                 0               1
1499           25.348017               1                 4               1

In [12]:
print("Missing values count:\n", data.isnull().sum())

Missing values count:
 Age                   150
Gender                150
AnnualIncome            0
NumberOfPurchases       0
ProductCategory         0
TimeSpentOnWebsite      0
LoyaltyProgram          0
DiscountsAvailed        0
PurchaseStatus          0
dtype: int64

In [13]:
data['Age'].mean()

44.404444444444444

In [14]:
# 숫자 데이터 전처리 - 결측값 처리 (평균값으로 대체)
data['Age'].fillna(data['Age'].mean(), inplace=True)

In [15]:
print("Missing values count:/n", data.isnull().sum())

Missing values count:/n Age                     0
Gender                150
AnnualIncome            0
NumberOfPurchases       0
ProductCategory         0
TimeSpentOnWebsite      0
LoyaltyProgram          0
DiscountsAvailed        0
PurchaseStatus          0
dtype: int64

In [16]:
data.tail(10)

,Age,Gender,AnnualIncome,NumberOfPurchases,ProductCategory,TimeSpentOnWebsite,LoyaltyProgram,DiscountsAvailed,PurchaseStatus
1490,44.404444,NaN,83126.660956,20,3,2.280306,0,1,0
1491,44.404444,NaN,71611.955361,20,1,38.681686,0,5,1
1492,63.000000,0.0,71874.591294,10,2,43.546243,0,1,0
1493,34.000000,1.0,20418.374269,9,1,54.459955,0,0,0
1494,34.000000,1.0,104649.186035,14,1,28.998117,0,1,0
1495,39.000000,1.0,65048.141834,13,0,34.590743,0,5,1
1496,67.000000,1.0,28775.331069,18,2,17.625707,0,1,1
1497,40.000000,1.0,57363.247541,7,4,12.206033,0,0,0
1498,63.000000,0.0,134021.775532,16,2,37.311634,1,0,1
1499,50.000000,0.0,52625.665974,13,0,25.348017,1,4,1

In [17]:
data['Gender'].mode()[0]

0.0

`data['Gender'].mode()[0]`는 파이썬에서 Pandas 라이브러리를 사용하여 특정 열의 최빈값(가장 자주 나타나는 값)을 구할 때 사용하는 구문입니다.

1. `data['Gender']`: 여기서 data는 Pandas의 DataFrame 객체를 의미합니다. 'Gender'는 이 DataFrame의 특정 열(column) 이름을 가리킵니다. 이 구문은 DataFrame에서 'Gender' 열에 해당하는 데이터를 선택합니다.

2. `mode()`: 이 메서드는 시리즈(Series)나 데이터프레임(DataFrame)의 최빈값을 계산합니다. mode() 메서드는 최빈값이 여러 개일 수 있기 때문에, 그 값을 모두 포함하는 시리즈(Series)를 반환합니다.

3. `[0]`: 최빈값이 여러 개일 경우, 시리즈의 첫 번째 값을 가져옵니다. 최빈값이 하나만 있더라도 이 부분은 첫 번째 값(즉, 유일한 최빈값)을 반환하게 됩니다.

따라서 `data['Gender'].mode()[0]`는 'Gender' 열에서 가장 자주 등장하는 값을 반환합니다.

In [18]:
data['Gender'].fillna(data['Gender'].mode()[0], inplace=True)

`inplace`는 Pandas에서 데이터를 처리할 때, 원래 데이터에 직접적으로 변경을 가할지를 결정하는 인자입니다. `inplace=True`로 설정하면, 해당 메서드는 변경된 데이터를 새로운 변수에 할당하지 않고, 원본 데이터 자체를 변경합니다.

구체적으로 `data['Gender'].fillna(data['Gender'].mode()[0], inplace=True)`에서:

- **`data['Gender']`**: 'Gender' 열을 선택합니다.
- **`fillna(data['Gender'].mode()[0])`**: 'Gender' 열에서 결측값(NA)을 'Gender' 열의 최빈값으로 채웁니다.
- **`inplace=True`**: 이 연산이 원본 `data` DataFrame의 'Gender' 열에 직접 적용됩니다. 즉, 원래 데이터가 수정됩니다.

반대로 `inplace=False` 또는 `inplace` 인자를 생략하면, `fillna` 메서드는 변경된 새로운 시리즈를 반환하고, 원본 `data`는 그대로 유지됩니다. 이 경우, 변경된 결과를 원본 데이터에 반영하려면 새로운 변수에 할당하거나, 기존 변수에 재할당해야 합니다.

In [19]:
print("Missing values count:\n", data.isnull().sum())

Missing values count:
 Age                   0
Gender                0
AnnualIncome          0
NumberOfPurchases     0
ProductCategory       0
TimeSpentOnWebsite    0
LoyaltyProgram        0
DiscountsAvailed      0
PurchaseStatus        0
dtype: int64

In [20]:
data['Gender'].head()

0    1.0
1    1.0
2    1.0
3    1.0
4    1.0
Name: Gender, dtype: float64

In [21]:
data['Gender'] = ['Male' if gender == 0 else 'Female' for gender in data['Gender']]
data['Gender'].head()

0    Female
1    Female
2    Female
3    Female
4    Female
Name: Gender, dtype: object

In [22]:
# 범주형 데이터 인코딩 (레이블 인코딩)
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data['Gender'] = le.fit_transform(data['Gender']) # 레이블 인코딩(Alphabetic)

LabelEncoder는 Scikit-learn 라이브러리에서 제공하는 클래스 중 하나로, 범주형 데이터를 숫자로 변환하는데 사용됩니다.

이 과정은 "레이블 인코딩"이라고 부르며, 머신 러닝 모델이 데이터를 더 잘 이해하고 처리할 수 있도록 도와줍니다.
- `le = LabelEncoder()`: LabelEncoder의 인스턴스를 생성합니다. 이제 le라는 객체를 통해 인코딩 작업을 수행할 수 있습니다.
- `data['Gender'] = le.fit_transform(data['Gender'])`:
    - `data['Gender']`: 'Gender' 열을 선택합니다.
    - `le.fit_transform(data['Gender'])`:
        - fit_transform 메서드는 두 가지 작업을 수행합니다. 먼저 fit 부분에서 'Gender' 열의 고유한 값(예: 'Male', 'Female')을 학습하고, transform 부분에서 이 값을 숫자 레이블로 변환합니다.
        - 예를 들어, 'Male'을 0으로, 'Female'을 1로 변환할 수 있습니다. 이 숫자 값들은 단순히 고유한 범주형 값을 나타내며, 숫자 사이의 관계나 순서를 나타내지 않습니다.
        
최종적으로, data['Gender'] 열은 범주형 문자열 값 대신 정수로 된 레이블로 바뀝니다. 예를 들어 'Male'과 'Female'이 각각 0과 1로 변환될 수 있습니다. 이는 머신 러닝 모델이 데이터를 효율적으로 처리할 수 있도록 돕습니다.

In [23]:
data['Gender'].head()

0    0
1    0
2    0
3    0
4    0
Name: Gender, dtype: int64

In [24]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

# 현재 시간
current_time = datetime.now()

# 예시 데이터 생성
time_data = pd.DataFrame({
    'PurchaseTime': [current_time - timedelta(edays=i) for i in range(5)],
    'DeliveryTime': [current_time + timedelta(days=i) for i in range(5)]
})

print("Original Data:\n", time_data)

Original Data:
                 PurchaseTime               DeliveryTime
0 2024-08-01 01:29:16.771849 2024-08-01 01:29:16.771849
1 2024-07-31 01:29:16.771849 2024-08-02 01:29:16.771849
2 2024-07-30 01:29:16.771849 2024-08-03 01:29:16.771849
3 2024-07-29 01:29:16.771849 2024-08-04 01:29:16.771849
4 2024-07-28 01:29:16.771849 2024-08-05 01:29:16.771849

이 코드는 Pandas와 NumPy 라이브러리, 그리고 `datetime` 모듈을 사용하여 시간과 관련된 예시 데이터를 생성하는 예제입니다.

1. **라이브러리 임포트**:
    
    ```python
    import pandas as pd
    import numpy as np
    from datetime import datetime, timedelta
    ```
    
    - `pandas as pd`: Pandas는 데이터 조작 및 분석을 위한 라이브러리입니다. `pd`라는 별칭으로 불러옵니다.
    - `numpy as np`: NumPy는 수치 계산을 위한 라이브러리로, `np`라는 별칭으로 불러옵니다.
    - `from datetime import datetime, timedelta`: `datetime` 모듈은 날짜와 시간 데이터를 처리하는 데 사용되며, `timedelta`는 두 날짜 사이의 차이를 표현합니다.
2. **현재 시간 가져오기**:
    
    ```python
    current_time = datetime.now()
    ```
    
    - `datetime.now()`는 현재 날짜와 시간을 반환합니다. 이 값은 `current_time` 변수에 저장됩니다.
3. **예시 데이터 생성**:
    
    ```python
    time_data = pd.DataFrame({
        'PurchaseTime': [current_time - timedelta(days=i) for i in range(5)],
        'DeliveryTime': [current_time + timedelta(days=i) for i in range(5)]
    })
    ```
    
    - `pd.DataFrame`: Pandas의 DataFrame 객체를 생성합니다.
    - `'PurchaseTime'`: 이 열은 지난 5일 동안의 시간을 나타내며, 현재 시간에서 하루씩 줄어든 값을 갖습니다.
        - `[current_time - timedelta(days=i) for i in range(5)]`: 리스트 내포(list comprehension) 구문을 사용하여 현재 시간에서 `i`일 이전의 시간을 계산합니다. `timedelta(days=i)`는 현재 시간에서 `i`일을 뺀 시간을 의미합니다.
    - `'DeliveryTime'`: 이 열은 향후 5일 동안의 시간을 나타내며, 현재 시간에서 하루씩 더해진 값을 갖습니다.
        - `[current_time + timedelta(days=i) for i in range(5)]`: 이 구문은 현재 시간에서 `i`일을 더한 시간을 계산합니다.
4. **데이터 출력**:
    
    ```python
    print("Original Data:\n", time_data)
    ```
    
    - 생성된 `time_data` DataFrame을 출력합니다. 이 DataFrame에는 'PurchaseTime'과 'DeliveryTime'이라는 두 개의 열이 있으며, 각 열은 5개의 날짜/시간 데이터를 포함합니다. 'PurchaseTime' 열은 현재 시간에서 과거로, 'DeliveryTime' 열은 현재 시간에서 미래로 향하는 날짜를 표시합니다.

In [25]:
# 시간 데이터를 datetime 형식으로 변환 (이미 datetime)
time_data['PurchaseTime'] = pd.to_datetime(time_data['PurchaseTime'])
time_data['PurchaseTime'] = pd.to_datetime(time_data['PurchaseTime'])

# 시간 컴포넌트 추출
time_data['PurchaseYear'] = time_data['PurchaseTime'].dt.year
time_data['PurchaseMonth'] = time_data['PurchaseTime'].dt.month
time_data['PurchaseDay'] = time_data['PurchaseTime'].dt.day
time_data['PurchaseHour'] = time_data['PurchaseTime'].dt.hour
time_data['PurchaseMinute'] = time_data['PurchaseTime'].dt.minute
time_data['PurchaseSecond'] = time_data['PurchaseTime'].dt.second

time_data['DeliveryDays'] = (time_data['DeliveryTime'] - time_data['PurchaseTime']).dt.days

print("\nData after extracting components and calculating differences:\n", time_data)

Data after extracting components and calculating differences:
                 PurchaseTime               DeliveryTime  PurchaseYear  \
0 2024-08-01 01:29:16.771849 2024-08-01 01:29:16.771849          2024
1 2024-07-31 01:29:16.771849 2024-08-02 01:29:16.771849          2024
2 2024-07-30 01:29:16.771849 2024-08-03 01:29:16.771849          2024
3 2024-07-29 01:29:16.771849 2024-08-04 01:29:16.771849          2024
4 2024-07-28 01:29:16.771849 2024-08-05 01:29:16.771849          2024

   PurchaseMonth  PurchaseDay  PurchaseHour  PurchaseMinute  PurchaseSecond  \
0              8            1             1              29              16
1              7           31             1              29              16
2              7           30             1              29              16
3              7           29             1              29              16
4              7           28             1              29              16

   DeliveryDays
0             0
1             2
2             4
3             6
4             8

In [26]:
# 데이터 스케일링
from sklearn.preprocessing import StandardScaler # standardize
print("Data before scaling:\n", data[['Age', 'AnnualIncome']].head())

scaler = StandardScaler() # 객체 생성
data[['Age', 'AnnualIncome']] = scaler.fit_transform(data[['Age', 'AnnualIncome']]) # 스케일링

print("Data after scaling:\n", data[['Age', 'AnnualIncome']].head())

Data before scaling:
     Age   AnnualIncome
0  40.0   66120.267939
1  20.0   23579.773583
2  27.0  127821.306432
3  24.0  137798.623120
4  31.0   99300.964220
Data after scaling:
         Age  AnnualIncome
0 -0.300467     -0.481934
1 -1.664846     -1.612821
2 -1.187314      1.158311
3 -1.391970      1.423546
4 -0.914438      0.400133

위의 코드는 데이터 전처리 과정 중 하나인 스케일링을 수행하는 방법을 보여줍니다.

1. **StandardScaler 사용**: `StandardScaler`는 데이터를 표준화(standardize)하기 위해 사용됩니다. 표준화는 각 특징을 평균이 0이고 표준편차가 1이 되도록 변환하는 과정입니다. 이는 모델 훈련 시 모든 특징이 동일한 스케일에 있을 때 성능이 향상되는 경우에 유용합니다.
2. **fit_transform 메서드**: `fit_transform` 메서드는 두 가지 작업을 동시에 수행합니다. 먼저, `fit` 부분에서는 주어진 데이터의 평균과 표준편차를 계산하여 학습하고, `transform` 부분에서는 이 학습된 평균과 표준편차를 사용하여 데이터를 변환합니다. 이 과정에서 데이터는 표준 정규 분포를 따르게 됩니다.
3. **데이터 프레임에 반영**: 원래 데이터 프레임의 'Age'와 'AnnualIncome' 열이 표준화된 값으로 교체됩니다. 이를 통해 모델이 학습할 때 각 특징이 균일한 중요도를 가지게 됩니다.

이러한 표준화 과정은 특히 데이터의 크기 차이가 큰 경우 유용하며, 머신러닝 알고리즘의 성능과 수렴 속도를 향상시킬 수 있습니다.

In [29]:
print("Original table:\n", data.head())
print("\n")

# 데이터 피벗
pivot_table = data.pivot_table(values='AnnualIncome', index='ProductCategory', columns='PurchaseStatus', aggfunc='mean') # aggfunc: 집계함수
print("Pivot table:\n", pivot_table.head())

Original table:
         Age  Gender  AnnualIncome  NumberOfPurchases  ProductCategory  \
0 -0.300467       0     -0.481934                  8                0
1 -1.664846       0     -1.612821                  4                2
2 -1.187314       0      1.158311                 11                2
3 -1.391970       0      1.423546                 19                3
4 -0.914438       0      0.400133                 19                1

   TimeSpentOnWebsite  LoyaltyProgram  DiscountsAvailed  PurchaseStatus
0           30.568601               0                 5               1
1           38.240097               0                 5               0
2           31.633212               1                 0               1
3           46.167059               0                 4               1
4           19.823592               0                 0               1


Pivot table:
 PurchaseStatus          0         1
ProductCategory
0               -0.176827  0.244683
1               -0.258843  0.114289
2               -0.050934  0.210538
3               -0.227139  0.228702
4               -0.104131  0.295883

- 피벗 테이블 생성:
    - `pivot_table = data.pivot_table(values='AnnualIncome', index='ProductCategory', columns='PurchaseStatus', aggfunc='mean')`는 피벗 테이블을 생성합니다.
    - `values='AnnualIncome'`: 피벗 테이블에서 관심 있는 값, 즉 'AnnualIncome'의 값을 보여줍니다.
    - `index='ProductCategory'`: 행 레벨을 설정하는 열입니다. 여기서는 'ProductCategory'를 기준으로 합니다.
    - `columns='PurchaseStatus'`: 열 레벨을 설정하는 열입니다. 'PurchaseStatus'에 따라 열이 나뉩니다.
    - `aggfunc='mean'`: 집계 함수를 지정합니다. 여기서는 평균(mean)을 사용하여 같은 'ProductCategory'와 'PurchaseStatus' 조합에 대한 평균 'AnnualIncome'을 계산합니다.

피벗 테이블을 사용하면 데이터의 특정 측면을 더 쉽게 분석하고 비교할 수 있습니다.

여기서는 'ProductCategory'와 'PurchaseStatus'에 따른 평균 연간 소득을 비교할 수 있습니다.

다중 인덱스 사용가능! (ex. index에 두 개 이상의 열 지정, column에 두 개 이상의 열 지정)

피벗 테이블은 데이터를 요약하고 분석하는 데 유용한 도구로, 주로 다음과 같은 목적을 위해 사용됩니다:

1. 데이터 요약: 피벗 테이블은 대량의 데이터를 간결하고 구조화된 방식으로 요약할 수 있습니다. 예를 들어, 특정 카테고리별로 평균, 합계, 최대값 등을 계산하여 중요한 통계 정보를 한눈에 파악할 수 있습니다.

2. 데이터 분석 및 비교: 피벗 테이블은 여러 범주(예: 'ProductCategory'와 'PurchaseStatus')에 따라 데이터를 분류하고, 이를 기준으로 값(예: 'AnnualIncome')을 비교할 수 있게 합니다. 이는 데이터의 패턴, 트렌드, 차이점을 식별하는 데 도움이 됩니다.

3. 의사결정 지원: 비즈니스 환경에서 피벗 테이블은 중요한 의사결정을 지원합니다. 예를 들어, 특정 제품 카테고리가 가장 높은 수익을 창출하는지, 특정 구매 상태가 더 나은 성과를 보이는지 등을 쉽게 분석할 수 있습니다.

4. 데이터 필터링 및 탐색: 피벗 테이블을 사용하면 특정 조건에 맞는 데이터를 쉽게 필터링하고 탐색할 수 있습니다. 이는 복잡한 데이터 세트를 다룰 때 특히 유용합니다.

이러한 이유로 피벗 테이블은 데이터 분석과 비즈니스 인텔리전스 작업에서 매우 유용한 도구로 널리 사용됩니다.

In [31]:
# 데이터 합치기

# 예제 데이터프레임 생성
data_1 = data[['Age', 'PurchaseStatus', 'AnnualIncome']]

# data_1 데이터 형태
print("Original data_1:\n", data_1.head())

data_2 = data[['Gender', 'AnnualIncome']]

# data_2 데이터 형태
print("Original data_2:\n", data_2.head())

merged_data = pd.merge(data_1, data_2, on='AnnualIncome')
print("Merged data:\n", merged_data.head())

Original data_1:
         Age  PurchaseStatus  AnnualIncome
0 -0.300467               1     -0.481934
1 -1.664846               0     -1.612821
2 -1.187314               1      1.158311
3 -1.391970               1      1.423546
4 -0.914438               1      0.400133
Original data_2:
    Gender  AnnualIncome
0       0     -0.481934
1       0     -1.612821
2       0      1.158311
3       0      1.423546
4       0      0.400133
Merged data:
         Age  PurchaseStatus  AnnualIncome  Gender
0 -0.300467               1     -0.481934       0
1 -1.664846               0     -1.612821       0
2 -1.187314               1      1.158311       0
3 -1.391970               1      1.423546       0
4 -0.914438               1      0.400133       0

In [32]:
# 데이터 그룹화
grouped_data = data.groupby('Gender').agg({'AnnualIncome': 'mean', 'Age': 'mean'})
print("Grouped data:\n", grouped_data)

Grouped data:
         AnnualIncome       Age
Gender
0           0.005859  0.016575
1          -0.004793 -0.013561

데이터 프레임에서 특정 열을 기준으로 데이터를 그룹화하고, 각 그룹에 대해 지정된 통계 정보를 계산하는 방법을 보여줍니다.

1. 데이터 그룹화:
    - `grouped_data = data.groupby('Gender')는 'Gender'` 열을 기준으로 데이터를 그룹화합니다. 이 과정에서 동일한 'Gender' 값을 가진 행들이 하나의 그룹으로 묶입니다.
2. 집계 함수 적용:
    - `.agg({'AnnualIncome': 'mean', 'Age': 'mean'})`는 각 그룹에 대해 특정 열의 통계 값을 계산합니다. 여기서 사용된 사전`({'AnnualIncome': 'mean', 'Age': 'mean'})`은 계산하고자 하는 열과 적용할 집계 함수를 지정합니다.
    - 'AnnualIncome'과 'Age' 열에 대해 평균(mean) 값을 계산하도록 지정되어 있습니다.
3. 결과 출력:
    - print("Grouped data:\n", grouped_data)는 그룹화와 집계가 완료된 결과를 출력합니다. 결과는 각 'Gender' 그룹별로 'AnnualIncome'과 'Age'의 평균 값을 포함합니다.

이러한 그룹화 및 집계는 데이터 분석에서 매우 유용합니다. 특정 그룹(여기서는 성별)에 대한 다양한 통계적 통찰을 얻을 수 있으며, 그룹 간의 차이점을 비교하거나 특정 패턴을 발견하는 데 도움이 됩니다.

In [34]:
data = pd.read_csv('customer_purchase_data.csv')
data.head()

,Age,Gender,AnnualIncome,NumberOfPurchases,ProductCategory,TimeSpentOnWebsite,LoyaltyProgram,DiscountsAvailed,PurchaseStatus
0,40,1,66120.267939,8,0,30.568601,0,5,1
1,20,1,23579.773583,4,2,38.240097,0,5,0
2,27,1,127821.306432,11,2,31.633212,1,0,1
3,24,1,137798.623120,19,3,46.167059,0,4,1
4,31,1,99300.964220,19,1,19.823592,0,0,1

In [36]:
# 파생 변수 생성
data['AgeGroup'] = pd.cut(data['Age'], bins=[0, 18, 35, 50, 100], labels=['Child', 'Yound Adult', 'Adult', 'Senoir'])
print("Data with AgeGroup:\n", data[['Age', 'AgeGroup']].head())

Data with AgeGroup:
    Age     AgeGroup
0   40        Adult
1   20  Yound Adult
2   27  Yound Adult
3   24  Yound Adult
4   31  Yound Adult

이 코드는 'Age' 열을 기준으로 나이대를 구분하는 파생 변수 'AgeGroup'을 생성합니다.

파생 변수는 원본 데이터에서 새로운 정보를 도출해내기 위해 추가되는 열입니다.

1. `pd.cut` 함수 사용:
    - `pd.cut(data['Age'], bins=[0, 18, 35, 50, 100], labels=['Child', 'Young Adult', 'Adult', 'Senior'])`는 Age 열의 값을 'Child', 'Young Adult', 'Adult', 'Senior'와 같은 나이대 그룹으로 구분합니다.
    - `bins` 매개변수는 숫자 범위를 정의합니다. 여기서는 `[0, 18, 35, 50, 100]`로 설정되어 있습니다. 이 범위는 다음과 같이 구분됩니다:
        - 0 <= Age < 18: 'Child'
        - 18 <= Age < 35: 'Young Adult'
        - 35 <= Age < 50: 'Adult'
        - 50 <= Age <= 100: 'Senior'
    - `labels` 매개변수는 각 범위에 할당될 이름을 지정합니다.
2. 파생 변수 `'AgeGroup'` 생성:
    - 이 함수는 지정된 범위와 레이블에 따라 각 'Age' 값에 대해 해당하는 나이대 그룹을 할당합니다. 이 결과는 새로운 열 'AgeGroup'으로 추가됩니다.

이 방법은 데이터를 보다 쉽게 분석할 수 있도록 그룹화하는 데 유용하며, 특정 연령대에 따른 행동, 특성, 성과 등을 분석하는 데 활용될 수 있습니다.

In [37]:
# 데이터 샘플링
sampled_data = data.sample(frac=0.1, random_state=42)
print("Sampled data:\n", sampled_data.head())
print("*"*30)
print("Sampled data info:\n", sampled_data.info())

Sampled data:
       Age  Gender  AnnualIncome  NumberOfPurchases  ProductCategory  \
1116   42       1  68609.736112                 12                3
1368   63       0  85623.427780                 18                0
422    22       1  51251.858676                  4                1
413    39       1  32791.434463                 18                2
451    39       1  75573.659430                 12                4

      TimeSpentOnWebsite  LoyaltyProgram  DiscountsAvailed  PurchaseStatus  \
1116           23.396362               1                 5               1
1368           11.657565               0                 1               0
422            46.090844               0                 0               0
413             1.137081               0                 1               0
451            49.085904               1                 3               1

         AgeGroup
1116        Adult
1368       Senoir
422   Yound Adult
413         Adult
451         Adult
******************************
<class 'pandas.core.frame.DataFrame'>
Index: 150 entries, 1116 to 782
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Age                 150 non-null    int64
 1   Gender              150 non-null    int64
 2   AnnualIncome        150 non-null    float64
 3   NumberOfPurchases   150 non-null    int64
 4   ProductCategory     150 non-null    int64
 5   TimeSpentOnWebsite  150 non-null    float64
 6   LoyaltyProgram      150 non-null    int64
 7   DiscountsAvailed    150 non-null    int64
 8   PurchaseStatus      150 non-null    int64
 9   AgeGroup            150 non-null    category
dtypes: category(1), float64(2), int64(7)
memory usage: 12.1 KB
Sampled data info:
 None

In [39]:
# PCA (주성분 분석)
from sklearn.decomposition import PCA

# PCA 적용
pca = PCA(n_components=2)
pca_result = pca.fit_transform(data[['Age', 'AnnualIncome', 'NumberOfPurchases']])

# 결과를 데이터프레임으로 변환
pca_df = pd.DataFrame(pca_result, columns=['PC1', 'PC2'])

print("PCA Result:\n", pca_df.head())

PCA Result:
             PC1        PC2
0 -18128.896428   4.133498
1 -60669.390919  23.773262
2  43572.141975  17.601737
3  53549.458643  20.806253
4  15051.799792  13.546052

이 코드는 주성분 분석(PCA, Principal Component Analysis)을 사용하여 다차원 데이터를 2차원으로 축소하는 과정입니다. PCA는 데이터의 분산을 최대화하는 새로운 축(주성분)을 찾아 원래의 고차원 데이터를 이 축으로 변환함으로써 차원을 축소하는 기법입니다.

여기서는 주성분 분석(PCA)을 사용하여 'Age', 'AnnualIncome', 'NumberOfPurchases' 세 개의 특징(변수)을 두 개의 주성분(PC1, PC2)으로 줄였습니다. 이는 원래의 세 차원 공간에서의 데이터를 두 차원 공간으로 축소한 것입니다.

1. PCA 모듈 임포트:
    - from sklearn.decomposition import PCA는 scikit-learn 라이브러리에서 PCA 클래스를 가져옵니다.
2. PCA 객체 생성:
    - pca = PCA(n_components=2)는 PCA 객체를 생성하며, n_components=2는 두 개의 주성분을 생성하도록 설정합니다. 즉, 원래 3차원 데이터를 2차원으로 축소합니다.
3. PCA 적용:
    - pca_result = pca.fit_transform(data[['Age', 'AnnualIncome', 'NumberOfPurchases']])는 PCA를 'Age', 'AnnualIncome', 'NumberOfPurchases' 열에 대해 적용합니다.
    - fit_transform 메서드는 먼저 데이터를 PCA 모델에 맞추고(fit), 그런 다음 데이터를 주성분 축으로 변환(transform)하여 새로운 2차원 공간에서의 좌표를 제공합니다. 이 좌표가 pca_result에 저장됩니다.
4. 결과를 데이터프레임으로 변환:
    - pca_df = pd.DataFrame(pca_result, columns['PC1', 'PC2'])는 PCA 결과를 pca_df라는 데이터프레임으로 변환하고, 새로운 열을 'PC1'과 'PC2'(첫 번째와 두 번째 주성분)로 명명합니다.

이 과정을 통해 데이터의 주요 분산을 설명하는 2차원 좌표가 생성됩니다. PCA는 데이터 시각화, 차원 축소, 잡음 제거 등 다양한 분석 목적에 유용하게 활용될 수 있습니다.

주성분 분석(PCA)을 사용하여 'Age', 'AnnualIncome', 'NumberOfPurchases' 세 개의 특징(변수)을 두 개의 주성분(PC1, PC2)으로 줄였습니다. 이는 원래의 세 차원 공간에서의 데이터를 두 차원 공간으로 축소한 것입니다.

이 과정이 의미하는 바는 다음과 같습니다:

1. **차원 축소**: 원래의 세 개의 변수('Age', 'AnnualIncome', 'NumberOfPurchases')는 각각 서로 다른 측면의 정보를 담고 있습니다. PCA는 이 세 개의 변수들 간의 상관 관계를 분석하여, 그 정보의 대부분을 설명하는 두 개의 새로운 변수(주성분)를 생성합니다. 이렇게 하면 데이터의 차원을 줄이면서도 원래 데이터가 가지고 있던 정보(분산)를 최대한 보존할 수 있습니다.
2. **주성분의 의미**: 생성된 두 개의 주성분(PC1, PC2)은 원래 변수들의 선형 결합으로 표현됩니다. 각 주성분은 원래 변수들의 가중합으로 이루어져 있으며, 각 주성분의 방향과 크기는 데이터의 분산을 최대한 설명하는 방향으로 설정됩니다. 즉, 첫 번째 주성분(PC1)은 데이터의 분산을 가장 많이 설명하는 축을 나타내고, 두 번째 주성분(PC2)은 그 다음으로 많이 설명하는 축을 나타냅니다.
3. **데이터 시각화 및 분석 용이성**: 차원 축소 후의 데이터는 두 개의 주성분(PC1, PC2)으로 표현되며, 이를 통해 데이터를 2차원 평면에 시각화할 수 있습니다. 시각화를 통해 데이터의 패턴, 군집 구조, 이상치 등을 더 쉽게 파악할 수 있습니다. 또한, 차원을 줄임으로써 기계 학습 모델의 훈련 시간을 단축하고 과적합을 방지하는 등의 이점도 있습니다.

PCA(주성분 분석, Principal Component Analysis)는 고차원 데이터를 더 낮은 차원으로 축소하면서도 원래 데이터의 분산(정보량)을 최대한 보존하는 통계적 기법입니다.

PCA는 데이터 시각화, 잡음 제거, 특징 추출, 데이터 압축 등의 다양한 용도로 활용됩니다. 특히, 고차원 데이터를 2차원이나 3차원으로 축소하여 시각적으로 분석하거나, 기계 학습 알고리즘의 성능을 향상시키기 위해 데이터의 차원을 축소할 때 유용합니다.

In [40]:
# 전처리 작업의 자동화 (파이프라인 구축)
from sklearn.pipeline import Pipeline # 파이프라인 구축을 위한 클래스
from sklearn.impute import SimpleImputer # 결측값 처리
from sklearn.preprocessing import StandardScaler # 데이터 스케일링

# 예제를 위한 데이터 분리
data_1 = data[['Age', 'AnnualIncome', 'NumberOfPurchases']]

# 파이프라인 구축
pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='mean')), # 결측값 대체
    ('scaler', StandardScaler()) # 데이터 스케일링
])

# 데이터 변환
processed_data = pipeline.fit_transform(data_1)

# 결과를 데이터프레임으로 반환
processed_data_df = pd.DataFrame(processed_data, columns=['Age', 'AnnualIncome', 'NumberOfPurchase'])

print("Processed Data:\n", processed_data_df.head())

Processed Data:
         Age  AnnualIncome  NumberOfPurchase
0 -0.276761     -0.481934         -0.411185
1 -1.564418     -1.612821         -1.090830
2 -1.113738      1.158311          0.098548
3 -1.306887      1.423546          1.457838
4 -0.856207      0.400133          1.457838

위의 코드는 `Pipeline`을 사용하여 데이터 전처리 작업을 일련의 단계로 구성한 것입니다. `Pipeline`은 머신러닝 작업에서 여러 단계의 변환 과정을 순차적으로 처리할 수 있도록 해주는 유용한 도구입니다. 각 단계는 특정한 데이터 처리 작업을 수행하며, 이 작업들이 파이프라인 내에서 체인처럼 연결됩니다.

1. **SimpleImputer (결측값 대체)**:
    - `('imputer', SimpleImputer(strategy='mean'))`는 결측값을 대체하기 위한 단계입니다.
    - `SimpleImputer`는 데이터셋에서 결측값(NaN)을 처리하기 위해 사용되며, `strategy='mean'` 옵션을 통해 결측값을 해당 열의 평균값으로 대체합니다. 이렇게 하면 결측값으로 인해 분석에서 중요한 데이터를 잃는 것을 방지할 수 있습니다.
2. **StandardScaler (데이터 스케일링)**:
    - `('scaler', StandardScaler())`는 데이터의 스케일을 표준화하는 단계입니다.
    - `StandardScaler`는 각 특징의 값을 평균이 0, 표준편차가 1이 되도록 변환합니다. 이는 머신러닝 모델의 성능을 개선하는 데 유용합니다, 특히 거리 기반 알고리즘에서 중요한 역할을 합니다.
3. 데이터 변환:
    - `pipeline.fit_transform(data_1)`: 주어진 데이터를 파이프라인의 각 단계에 맞춰 변환합니다. fit은 각 단계에서 필요한 학습(예: 평균, 표준편차 계산)을 수행하고, transform은 이 학습된 정보를 바탕으로 데이터를 변환합니다.


파이프라인의 이점은 여러 전처리 단계를 체계적으로 관리하고, 데이터를 처리하는 과정을 재사용 가능하게 한다는 것입니다. 이렇게 하면 코드의 가독성과 유지보수성을 높일 수 있으며, 데이터 전처리와 모델 훈련을 통합적으로 관리할 수 있습니다. 예를 들어, 훈련 데이터와 테스트 데이터에 대해 동일한 전처리 단계를 일관되게 적용할 수 있습니다.