2024.07.03 (수) - DAY2 데이터 활용 및 구현 2 / 이론 실습

https://www.kaggle.com/datasets/rabieelkharoua/predict-customer-purchase-behavior-dataset

In [ ]:
!pip install kaggle

Requirement already satisfied: kaggle in /usr/local/lib/python3.10/dist-packages (1.6.17)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.10/dist-packages (from kaggle) (1.16.0)
Requirement already satisfied: certifi>=2023.7.22 in /usr/local/lib/python3.10/dist-packages (from kaggle) (2024.7.4)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.10/dist-packages (from kaggle) (2.8.2)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from kaggle) (2.31.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from kaggle) (4.66.4)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.10/dist-packages (from kaggle) (8.0.4)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.10/dist-packages (from kaggle) (2.0.7)
Requirement already satisfied: bleach in /usr/local/lib/python3.10/dist-packages (from kaggle) (6.1.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.10/dist-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.10/dist-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->kaggle) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->kaggle) (3.7)

In [ ]:
!kaggle datasets download -d rabieelkharoua/predict-customer-purchase-behavior-dataset

Dataset URL: https://www.kaggle.com/datasets/rabieelkharoua/predict-customer-purchase-behavior-dataset
License(s): Attribution 4.0 International (CC BY 4.0)
Downloading predict-customer-purchase-behavior-dataset.zip to /content
  0% 0.00/35.1k [00:00<?, ?B/s]
100% 35.1k/35.1k [00:00<00:00, 34.6MB/s]

In [ ]:
!unzip predict-customer-purchase-behavior-dataset.zip

Archive:  predict-customer-purchase-behavior-dataset.zip
  inflating: customer_purchase_data.csv

In [ ]:
# pandas 라이브러리 사용
import pandas as pd

# CSV load
data = pd.read_csv('customer_purchase_data.csv')

In [ ]:
# 데이터 구조 확인
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Age                 1500 non-null   int64
 1   Gender              1500 non-null   int64
 2   AnnualIncome        1500 non-null   float64
 3   NumberOfPurchases   1500 non-null   int64
 4   ProductCategory     1500 non-null   int64
 5   TimeSpentOnWebsite  1500 non-null   float64
 6   LoyaltyProgram      1500 non-null   int64
 7   DiscountsAvailed    1500 non-null   int64
 8   PurchaseStatus      1500 non-null   int64
dtypes: float64(2), int64(7)
memory usage: 105.6 KB

In [ ]:
# 데이터 샘플 확인
data.head(5)

,Age,Gender,AnnualIncome,NumberOfPurchases,ProductCategory,TimeSpentOnWebsite,LoyaltyProgram,DiscountsAvailed,PurchaseStatus
0,40,1,66120.267939,8,0,30.568601,0,5,1
1,20,1,23579.773583,4,2,38.240097,0,5,0
2,27,1,127821.306432,11,2,31.633212,1,0,1
3,24,1,137798.623120,19,3,46.167059,0,4,1
4,31,1,99300.964220,19,1,19.823592,0,0,1

In [ ]:
# 데이터 기초통계 확인
data.describe()

,Age,Gender,AnnualIncome,NumberOfPurchases,ProductCategory,TimeSpentOnWebsite,LoyaltyProgram,DiscountsAvailed,PurchaseStatus
count,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.00000
mean,44.298667,0.504667,84249.164338,10.420000,2.012667,30.469040,0.326667,2.555333,0.43200
std,15.537259,0.500145,37629.493078,5.887391,1.428005,16.984392,0.469151,1.705152,0.49552
min,18.000000,0.000000,20001.512518,0.000000,0.000000,1.037023,0.000000,0.000000,0.00000
25%,31.000000,0.000000,53028.979155,5.000000,1.000000,16.156700,0.000000,1.000000,0.00000
50%,45.000000,1.000000,83699.581476,11.000000,2.000000,30.939516,0.000000,3.000000,0.00000
75%,57.000000,1.000000,117167.772858,15.000000,3.000000,44.369863,1.000000,4.000000,1.00000
max,70.000000,1.000000,149785.176481,20.000000,4.000000,59.991105,1.000000,5.000000,1.00000

In [ ]:
# 결측값 확인
missing_values = data.isnull().sum()
print("Missing values in each column:\n", missing_values)

Missing values in each column:
 Age                   0
Gender                0
AnnualIncome          0
NumberOfPurchases     0
ProductCategory       0
TimeSpentOnWebsite    0
LoyaltyProgram        0
DiscountsAvailed      0
PurchaseStatus        0
dtype: int64

In [ ]:
import numpy as np

# 결측값 반환 함수
def add_missing_values(df, col_name, missing_frac):
    """
    특정 열에 지정된 비율의 결측값을 추가합니다.

    :param df: 데이터 프레임
    :param col_name: 결측값을 추가할 열 이름
    :param missing_frac: 결측값 비율 (0.0 ~ 1.0)
    """

    np.random.seed(42) # 재현성을 위해 랜덤 시드 설정
    n_rows = df.shape[0] # 데이터프레임의 행 수
    n_missing = int(n_rows * missing_frac) # 비율에 따라 결측값을 추가할 행의 수를 계산

    missing_indices = np.random.choice(n_rows, n_missing, replace=False) # 결측값을 추가할 행의 인덱스를 무작위로 선택
    df.loc[missing_indices, col_name] = np.nan # 선택된 인덱스의 열(col_name)에 NaN 값을 할당하여 결측값을 추가

missing_frac은 함수 add_missing_values를 호출할 때 인자로 전달됩니다. 이 인자는 결측값을 추가할 비율을 지정하며, 0.0과 1.0 사이의 값이어야 합니다. missing_frac이 0.0이면 결측값이 추가되지 않고, 1.0이면 해당 열의 모든 값이 결측값으로 설정됩니다. 사용자는 이 인자를 통해 원하는 결측값 비율을 설정할 수 있습니다.

In [ ]:
# 결측값 추가
add_missing_values(data, 'Age', 0.1) # Age 열에 10% 결측값 추가
add_missing_values(data, 'Gender', 0.1) # Gender 열에 10% 결측값 추가

In [ ]:
# 결측값이 잘 추가되었는지 확인
print("Data with missing values:\n", data.tail(10))

Data with missing values:
        Age  Gender   AnnualIncome  NumberOfPurchases  ProductCategory  \
1490   NaN     NaN   83126.660956                 20                3
1491   NaN     NaN   71611.955361                 20                1
1492  63.0     0.0   71874.591294                 10                2
1493  34.0     1.0   20418.374269                  9                1
1494  34.0     1.0  104649.186035                 14                1
1495  39.0     1.0   65048.141834                 13                0
1496  67.0     1.0   28775.331069                 18                2
1497  40.0     1.0   57363.247541                  7                4
1498  63.0     0.0  134021.775532                 16                2
1499  50.0     0.0   52625.665974                 13                0

      TimeSpentOnWebsite  LoyaltyProgram  DiscountsAvailed  PurchaseStatus
1490            2.280306               0                 1               0
1491           38.681686               0                 5               1
1492           43.546243               0                 1               0
1493           54.459955               0                 0               0
1494           28.998117               0                 1               0
1495           34.590743               0                 5               1
1496           17.625707               0                 1               1
1497           12.206033               0                 0               0
1498           37.311634               1                 0               1
1499           25.348017               1                 4               1

In [ ]:
print("Missing values count:\n", data.isnull().sum())

Missing values count:
 Age                   150
Gender                150
AnnualIncome            0
NumberOfPurchases       0
ProductCategory         0
TimeSpentOnWebsite      0
LoyaltyProgram          0
DiscountsAvailed        0
PurchaseStatus          0
dtype: int64

In [ ]:
data['Age'].mean()

44.404444444444444

In [ ]:
# 숫자 데이터 전처리 - 결측값 처리 (평균값으로 대체)
data['Age'].fillna(data['Age'].mean(), inplace=True)

In [ ]:
print("Missing values count:/n", data.isnull().sum())

Missing values count:/n Age                     0
Gender                150
AnnualIncome            0
NumberOfPurchases       0
ProductCategory         0
TimeSpentOnWebsite      0
LoyaltyProgram          0
DiscountsAvailed        0
PurchaseStatus          0
dtype: int64

In [ ]:
data.tail(10)

,Age,Gender,AnnualIncome,NumberOfPurchases,ProductCategory,TimeSpentOnWebsite,LoyaltyProgram,DiscountsAvailed,PurchaseStatus
1490,44.404444,NaN,83126.660956,20,3,2.280306,0,1,0
1491,44.404444,NaN,71611.955361,20,1,38.681686,0,5,1
1492,63.000000,0.0,71874.591294,10,2,43.546243,0,1,0
1493,34.000000,1.0,20418.374269,9,1,54.459955,0,0,0
1494,34.000000,1.0,104649.186035,14,1,28.998117,0,1,0
1495,39.000000,1.0,65048.141834,13,0,34.590743,0,5,1
1496,67.000000,1.0,28775.331069,18,2,17.625707,0,1,1
1497,40.000000,1.0,57363.247541,7,4,12.206033,0,0,0
1498,63.000000,0.0,134021.775532,16,2,37.311634,1,0,1
1499,50.000000,0.0,52625.665974,13,0,25.348017,1,4,1

In [ ]:
data['Gender'].mode()[0]

0.0

`data['Gender'].mode()[0]`는 파이썬에서 Pandas 라이브러리를 사용하여 특정 열의 최빈값(가장 자주 나타나는 값)을 구할 때 사용하는 구문입니다.

1. `data['Gender']`: 여기서 data는 Pandas의 DataFrame 객체를 의미합니다. 'Gender'는 이 DataFrame의 특정 열(column) 이름을 가리킵니다. 이 구문은 DataFrame에서 'Gender' 열에 해당하는 데이터를 선택합니다.

2. `mode()`: 이 메서드는 시리즈(Series)나 데이터프레임(DataFrame)의 최빈값을 계산합니다. mode() 메서드는 최빈값이 여러 개일 수 있기 때문에, 그 값을 모두 포함하는 시리즈(Series)를 반환합니다.

3. `[0]`: 최빈값이 여러 개일 경우, 시리즈의 첫 번째 값을 가져옵니다. 최빈값이 하나만 있더라도 이 부분은 첫 번째 값(즉, 유일한 최빈값)을 반환하게 됩니다.

따라서 `data['Gender'].mode()[0]`는 'Gender' 열에서 가장 자주 등장하는 값을 반환합니다.

In [ ]:
data['Gender'].fillna(data['Gender'].mode()[0], inplace=True)

`inplace`는 Pandas에서 데이터를 처리할 때, 원래 데이터에 직접적으로 변경을 가할지를 결정하는 인자입니다. `inplace=True`로 설정하면, 해당 메서드는 변경된 데이터를 새로운 변수에 할당하지 않고, 원본 데이터 자체를 변경합니다.

구체적으로 `data['Gender'].fillna(data['Gender'].mode()[0], inplace=True)`에서:

- **`data['Gender']`**: 'Gender' 열을 선택합니다.
- **`fillna(data['Gender'].mode()[0])`**: 'Gender' 열에서 결측값(NA)을 'Gender' 열의 최빈값으로 채웁니다.
- **`inplace=True`**: 이 연산이 원본 `data` DataFrame의 'Gender' 열에 직접 적용됩니다. 즉, 원래 데이터가 수정됩니다.

반대로 `inplace=False` 또는 `inplace` 인자를 생략하면, `fillna` 메서드는 변경된 새로운 시리즈를 반환하고, 원본 `data`는 그대로 유지됩니다. 이 경우, 변경된 결과를 원본 데이터에 반영하려면 새로운 변수에 할당하거나, 기존 변수에 재할당해야 합니다.

In [ ]:
print("Missing values count:\n", data.isnull().sum())

Missing values count:
 Age                   0
Gender                0
AnnualIncome          0
NumberOfPurchases     0
ProductCategory       0
TimeSpentOnWebsite    0
LoyaltyProgram        0
DiscountsAvailed      0
PurchaseStatus        0
dtype: int64

In [ ]:
data['Gender'].head()

0    1.0
1    1.0
2    1.0
3    1.0
4    1.0
Name: Gender, dtype: float64

In [ ]:
data['Gender'] = ['Male' if gender == 0 else 'Female' for gender in data['Gender']]
data['Gender'].head()

0    Female
1    Female
2    Female
3    Female
4    Female
Name: Gender, dtype: object

In [ ]:
# 범주형 데이터 인코딩 (레이블 인코딩)
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data['Gender'] = le.fit_transform(data['Gender']) # 레이블 인코딩(Alphabetic)

LabelEncoder는 Scikit-learn 라이브러리에서 제공하는 클래스 중 하나로, 범주형 데이터를 숫자로 변환하는데 사용됩니다. 이 과정은 "레이블 인코딩"이라고 부르며, 머신 러닝 모델이 데이터를 더 잘 이해하고 처리할 수 있도록 도와줍니다.
- le = LabelEncoder(): LabelEncoder의 인스턴스를 생성합니다. 이제 le라는 객체를 통해 인코딩 작업을 수행할 수 있습니다.
- data['Gender'] = le.fit_transform(data['Gender']):
    - data['Gender']: 'Gender' 열을 선택합니다.
    - le.fit_transform(data['Gender']):
        - fit_transform 메서드는 두 가지 작업을 수행합니다. 먼저 fit 부분에서 'Gender' 열의 고유한 값(예: 'Male', 'Female')을 학습하고, transform 부분에서 이 값을 숫자 레이블로 변환합니다.
        - 예를 들어, 'Male'을 0으로, 'Female'을 1로 변환할 수 있습니다. 이 숫자 값들은 단순히 고유한 범주형 값을 나타내며, 숫자 사이의 관계나 순서를 나타내지 않습니다.
        
최종적으로, data['Gender'] 열은 범주형 문자열 값 대신 정수로 된 레이블로 바뀝니다. 예를 들어 'Male'과 'Female'이 각각 0과 1로 변환될 수 있습니다. 이는 머신 러닝 모델이 데이터를 효율적으로 처리할 수 있도록 돕습니다.

In [ ]:
data['Gender'].head()

0    0
1    0
2    0
3    0
4    0
Name: Gender, dtype: int64

In [ ]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

# 현재 시간
current_time = datetime.now()

# 예시 데이터 생성
time_data = pd.DataFrame({
    'PurchaseTime': [current_time - timedelta(days=i) for i in range(5)],
    'DeliveryTime': [current_time + timedelta(days=i) for i in range(5)]
})

print("Original Data:\n", time_data)

Original Data:
                 PurchaseTime               DeliveryTime
0 2024-07-31 07:50:00.690402 2024-07-31 07:50:00.690402
1 2024-07-30 07:50:00.690402 2024-08-01 07:50:00.690402
2 2024-07-29 07:50:00.690402 2024-08-02 07:50:00.690402
3 2024-07-28 07:50:00.690402 2024-08-03 07:50:00.690402
4 2024-07-27 07:50:00.690402 2024-08-04 07:50:00.690402

이 코드는 Pandas와 NumPy 라이브러리, 그리고 `datetime` 모듈을 사용하여 시간과 관련된 예시 데이터를 생성하는 예제입니다. 코드의 각 부분에 대한 설명은 다음과 같습니다:

1. **라이브러리 임포트**:
    
    ```python
    import pandas as pd
    import numpy as np
    from datetime import datetime, timedelta
    ```
    
    - `pandas as pd`: Pandas는 데이터 조작 및 분석을 위한 라이브러리입니다. `pd`라는 별칭으로 불러옵니다.
    - `numpy as np`: NumPy는 수치 계산을 위한 라이브러리로, `np`라는 별칭으로 불러옵니다.
    - `from datetime import datetime, timedelta`: `datetime` 모듈은 날짜와 시간 데이터를 처리하는 데 사용되며, `timedelta`는 두 날짜 사이의 차이를 표현합니다.
2. **현재 시간 가져오기**:
    
    ```python
    current_time = datetime.now()
    ```
    
    - `datetime.now()`는 현재 날짜와 시간을 반환합니다. 이 값은 `current_time` 변수에 저장됩니다.
3. **예시 데이터 생성**:
    
    ```python
    time_data = pd.DataFrame({
        'PurchaseTime': [current_time - timedelta(days=i) for i in range(5)],
        'DeliveryTime': [current_time + timedelta(days=i) for i in range(5)]
    })
    ```
    
    - `pd.DataFrame`: Pandas의 DataFrame 객체를 생성합니다.
    - `'PurchaseTime'`: 이 열은 지난 5일 동안의 시간을 나타내며, 현재 시간에서 하루씩 줄어든 값을 갖습니다.
        - `[current_time - timedelta(days=i) for i in range(5)]`: 리스트 내포(list comprehension) 구문을 사용하여 현재 시간에서 `i`일 이전의 시간을 계산합니다. `timedelta(days=i)`는 현재 시간에서 `i`일을 뺀 시간을 의미합니다.
    - `'DeliveryTime'`: 이 열은 향후 5일 동안의 시간을 나타내며, 현재 시간에서 하루씩 더해진 값을 갖습니다.
        - `[current_time + timedelta(days=i) for i in range(5)]`: 이 구문은 현재 시간에서 `i`일을 더한 시간을 계산합니다.
4. **데이터 출력**:
    
    ```python
    print("Original Data:\n", time_data)
    ```
    
    - 생성된 `time_data` DataFrame을 출력합니다. 이 DataFrame에는 'PurchaseTime'과 'DeliveryTime'이라는 두 개의 열이 있으며, 각 열은 5개의 날짜/시간 데이터를 포함합니다. 'PurchaseTime' 열은 현재 시간에서 과거로, 'DeliveryTime' 열은 현재 시간에서 미래로 향하는 날짜를 표시합니다.

In [ ]:
# 시간 데이터를 datetime 형식으로 변환 (이미 datetime)
time_data['PurchaseTime'] = pd.to_datetime(time_data['PurchaseTime'])
time_data['PurchaseTime'] = pd.to_datetime(time_data['PurchaseTime'])

# 시간 컴포넌트 추출
time_data['PurchaseYear'] = time_data['PurchaseTime'].dt.year
time_data['PurchaseMonth'] = time_data['PurchaseTime'].dt.month
time_data['PurchaseDay'] = time_data['PurchaseTIme'].dt.day
time_data['PurchaseHour'] = time_data['PurchaseTIme'].dt.hour
time_data['PurchaseMinute'] = time_data['PurchaseTIme'].dt.minute
time_data['PurchaseSecond'] = time_data['PurchaseTIme'].dt.second

KeyError: 'PurchaseTIme'